# DEFAULT SETTING
[providers]
  [providers.file]
    filename = "/etc/traefik/dynamic-conf.toml"

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.web-secure]
    address = ":443"

[log]
  level = "INFO"

[certificatesResolvers]
  [certificatesResolvers.default]
    [certificatesResolvers.default.acme]
      email = "{{ cookiecutter.email }}"
      storage = "/etc/traefik/acme/acme.json"
      [certificatesResolvers.default.acme.httpChallenge]
        entryPoint = "web"



